version: '3.4'

services:
  mongo:
    image: mongo:4.2
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081' 

  rabbit:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'